//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTReporting.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://filehold/FH/FileHold/LibraryManager/DocumentSchemaManager.asmx")]
        public string EFTReporting_DocumentSchemaManagerService_DocumentSchemaManager {
            get {
                return ((string)(this["EFTReporting_DocumentSchemaManagerService_DocumentSchemaManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://filehold/FH/FileHold/LibraryManager/DocumentManager.asmx")]
        public string EFTReporting_DocumentManagerService_DocumentManager {
            get {
                return ((string)(this["EFTReporting_DocumentManagerService_DocumentManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://filehold/FH/FileHold/LibraryManager/DocumentFinder.asmx")]
        public string EFTReporting_DocumentFinderService_DocumentFinder {
            get {
                return ((string)(this["EFTReporting_DocumentFinderService_DocumentFinder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cgybackup/activedocsdev/adedocumentassembly.asmx")]
        public string EFTReporting_adeActiveDocs_adeDocumentAssembly {
            get {
                return ((string)(this["EFTReporting_adeActiveDocs_adeDocumentAssembly"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://filehold/FH/FileHold/LibraryManager/LibraryStructureManager.asmx")]
        public string EFTReporting_LibraryStructureManagerService_LibraryStructureManager {
            get {
                return ((string)(this["EFTReporting_LibraryStructureManagerService_LibraryStructureManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://filehold/FH/FileHold/DocumentRepository/RepositoryController.asmx")]
        public string EFTReporting_RepositoryControllerService_RepositoryController {
            get {
                return ((string)(this["EFTReporting_RepositoryControllerService_RepositoryController"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://filehold/FH/FileHold/UserRoleManager/SessionManager.asmx")]
        public string EFTReporting_SessionManagerService_SessionManager {
            get {
                return ((string)(this["EFTReporting_SessionManagerService_SessionManager"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://filehold/FH/FileHold/LibraryManager/UserPreferences.asmx")]
        public string EFTReporting_UserPreferencesService_UserPreferences {
            get {
                return ((string)(this["EFTReporting_UserPreferencesService_UserPreferences"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://filehold/FH/FileHold/UserRoleManager/WindowsLogin.asmx")]
        public string EFTReporting_WindowsLoginService_WindowsLogin {
            get {
                return ((string)(this["EFTReporting_WindowsLoginService_WindowsLogin"]));
            }
        }
    }
}
