//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVendLi_tbl_vw
    {
        public Nullable<byte> APVendorListStatus { get; set; }
        public long APVendorListID { get; set; }
        public string APVendorListNickName { get; set; }
        public string APVendorListSortName { get; set; }
        public Nullable<long> APVendorListPersonID { get; set; }
        public Nullable<int> APVendorListDiscDays1 { get; set; }
        public Nullable<float> APVendorListDiscPct1 { get; set; }
        public Nullable<int> APVendorListDiscDays2 { get; set; }
        public Nullable<float> APVendorListDiscPct2 { get; set; }
        public Nullable<int> APVendorListDiscDays3 { get; set; }
        public Nullable<float> APVendorListDiscPct3 { get; set; }
        public Nullable<double> APVendorListTotPurch { get; set; }
        public Nullable<double> APVendorListTotPybl { get; set; }
        public Nullable<double> APVendorListTotDisc { get; set; }
        public Nullable<long> APVendorListNextDueDate { get; set; }
        public Nullable<int> APVendorListActiveFlag { get; set; }
        public Nullable<long> APVendorListDefGLAcctID { get; set; }
        public Nullable<long> APVendorListDefActCode { get; set; }
        public Nullable<int> APVendorListDefGSTCat { get; set; }
        public Nullable<long> APVendorList1099BoxNum { get; set; }
        public Nullable<long> APVendorListExtraID1 { get; set; }
        public Nullable<long> APVendorListExtraID2 { get; set; }
        public Nullable<double> APVendorListExtraDbl { get; set; }
        public string APVendorListNotes { get; set; }
        public string APVendorListType1099 { get; set; }
        public string APVendorListID1099 { get; set; }
        public string APVendorListAcctNum { get; set; }
        public string APVendorListTerms { get; set; }
        public string APVendorListExtraString { get; set; }
    }
}
