//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInformation
    {
        public string CompanyCode { get; set; }
        public string CompanyFullName { get; set; }
        public string CompanyStreetAddress { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyProvince { get; set; }
        public string CompanyPostalCode { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyFax { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyAccountingEmail { get; set; }
    }
}
