//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFT_Reporting_VendorList_vw
    {
        public long APVendorListID { get; set; }
        public string APVendorListSortName { get; set; }
        public string AddressInfoAddrLine1 { get; set; }
        public string AddressInfoAddrLine2 { get; set; }
        public string AddressInfoCity { get; set; }
        public string AddressInfoProv { get; set; }
        public string AddressInfoCode { get; set; }
        public string AddressInfoCountry { get; set; }
    }
}
